# -*- coding: utf-8 -*-
{
    'name': 'Fleet Service Accounting',
    'summary': 'Fleet Service Accounting',
    'description': """Integration of fleet service with inventory and accounting""",
    'version': '1.0',
    'sequence': 1,
    'email': 'info@misnedtech.com ',
    'website':'https://misnedtech.com/',
    'category': 'Human Resources/Fleet',
    'author': 'Almisned Technology',
    'price': 150,
    'currency': 'EUR',
    'license': 'OPL-1',
    "live_test_url" : "",
    'depends': ['fleet',
                'stock',
                'purchase',
                'hr_expense',],
    'qweb': [],
    'data': [
        'security/ir.model.access.csv',
        'data/fleet_service_data.xml',
        'views/fleet_service_accounting.xml',
        'views/res_config_settings_views.xml',
    ],
    'images': [],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': False,
}
