# -*- coding: utf-8 -*-
{
    'name': 'Attendance Machine Integration',
    'summary': 'Attendance Machine Integration',
    'description': """Attendance Machine Integration with Odoo""",
    'version': '17.0',
    'sequence': 1,
    'email': 'info@misnedtech.com ',
    'website':'',
    'category': 'Human Resources/Attendances',
    'author': 'Almisned Technology',
    'price': 150,
    'currency': 'EUR',
    'license': 'OPL-1',
    "live_test_url" : "",
    'depends': ['hr_attendance',
                'hr_payroll'],
    'qweb': [],
    'data': [
        'security/ir.model.access.csv',
        'views/machine_data.xml',
        'views/resource_views.xml',
    #    'views/attendance_analysis_view.xml',
    #    'data/attendance_scheduler.xml',
    ],
    'images': [],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': False,
}
