# -*- coding: utf-8 -*-
{
    'name': 'Woqod Fuel Import',
    'summary': 'Woqod Fuel Import',
    'description': """Woqod Fuel Import""",
    'version': '19.01',
    'sequence': 1,
    'email': 'info@misnedtech.com ',
    'website':'',
    'category': 'Human Resources/Fleet',
    'author': 'Almisned Technology',
    'price': 15,
    'currency': 'EUR',
    'license': 'OPL-1',
    "live_test_url" : "",
    'depends': ['fleet',],
    'qweb': [],
    'data': [
        'security/ir.model.access.csv',
        'views/woqod_fuel_import.xml',
        'data/woqod_fuel_scheduler.xml',],
    'images': [],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': False,
}
