# -*- coding: utf-8 -*-
{
    'name': 'Maintenance Resourse Planner',
    'summary': 'Maintenance Resourse Planner',
    'description': """Enable planning and consumption of items for maintenance operations.""",
    'version': '1.0',
    'sequence': 1,
    'email': 'info@arcxion.com ',
    'website':'https://arcxion.com/',
    'category': 'Manufacturing/Maintenance',
    'author': 'Arcxion',
    'price': 150,
    'currency': 'EUR',
    'license': 'OPL-1',
    "live_test_url" : "",
    'depends': ['maintenance',
                'stock',
                'purchase',
                'hr_expense',],
    'qweb': [],
    'data': [
        'security/ir.model.access.csv',
        'data/maintenance_resource_planner_data.xml',
        'views/maintenance_resource_planner.xml',
    ],
    'images': [],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': False,
}
